 const dropdownOptions = {
  genders: ['Male', 'Female', 'Other'],
  ageGroups: ['18 - 25', '26 - 35', '36 - 45', '46 - 55', '56 and above'],
  maritalStatuses: ['Single', 'Married', 'Divorced', 'Widowed', 'Other'],
  areas: [
    'Lekki Phase 1',
    'Agungi',
    'Ajah',
    'Awoyaya',
    'Chevron',
    'Elegushi',
    'Eleko',
    'Falomo',
    'Ibeju Lekki',
    'Igbo Efon',
    'Ikate',
    'Ikota',
    'Ikoyi',
    'Ilasan',
    'Lagos Island (CMS, Apongbon)',
    'Lagos Mainland',
    'Marwa',
    'New Road',
    'Ologolo',
    'Oniru',
    'Oniru',
    'Outside Lagos',
    'Outside Nigeria',
    'Salem',
    'Sangotedo',
    'VGC',
    'Victoria Island',
    'Others'
  ],
};

module.exports = { dropdownOptions }